src/Entity/Membre.php
<?php

namespace App\Entity;

use App\Validator\Mdp;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MembreRepository")
 * @UniqueEntity("email")
 */
class Membre implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank()
     * @Assert\Length(max=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank()
     * @Assert\Length(max=50)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=100, unique=true)
     * @Assert\NotBlank()
     * @Assert\Length(max=100)
     */
    private $email;

    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min=8, max=255)
     * @Mdp()
     */
    private $mdp;

    /**
     * @var string The hashed password
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank()
     * @Assert\Length(max=100)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank()
     * @Assert\Length(max=50)
     */
    private $pays;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Personnalite")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank()
     */
    private $personnalite;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $photo_profil;

    /**
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(max=255)
     */
    private $statut;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_inscription;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description_photo;

    /**
     * @ORM\Column(type="string", length=10)
     * @Assert\NotBlank()
     * @Assert\Length(max=10)
     */
    private $role_emploi;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        $this->username = $this->email;
        return (string) $this->username;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        $this->password = $this->mdp;
        return (string) $this->password;
    }

    public function getMdp(): ?string
    {
        return $this->mdp;
    }

    public function setMdp(string $mdp): self
    {
        $this->mdp = $mdp;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getPersonnalite(): ?Personnalite
    {
        return $this->personnalite;
    }

    public function setPersonnalite(?Personnalite $personnalite): self
    {
        $this->personnalite = $personnalite;

        return $this;
    }

    public function getPhotoProfil(): ?string
    {
        return $this->photo_profil;
    }

    public function setPhotoProfil(?string $photo_profil): self
    {
        $this->photo_profil = $photo_profil;

        return $this;
    }

    /**
     * Get the value of imageFile
     *
     * @return  File
     */ 
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * Set the value of imageFile
     *
     * @param  File  $imageFile
     *
     * @return  self
     */ 
    public function setImageFile(File $imageFile)
    {
        $this->imageFile = $imageFile;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = explode(',', $this->statut);
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getDateInscription(): ?\DateTimeInterface
    {
        return $this->date_inscription;
    }

    public function setDateInscription(\DateTimeInterface $date_inscription): self
    {
        $this->date_inscription = $date_inscription;

        return $this;
    }

    public function getDescriptionPhoto(): ?string
    {
        return $this->description_photo;
    }

    public function setDescriptionPhoto(string $description_photo): self
    {
        $this->description_photo = $description_photo;

        return $this;
    }

    public function getRoleEmploi(): ?string
    {
        return $this->role_emploi;
    }

    public function setRoleEmploi(string $role_emploi): self
    {
        $this->role_emploi = $role_emploi;

        return $this;
    }
}

src/Controller/RecruteurFrontController.php
<?php
namespace App\Controller;
use App\Entity\Like;
use App\Repository\LikeRepository;
use App\Repository\CandidatRepository;
use App\Repository\RecruteurRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
class RecruteurFrontController extends AbstractController
{
    public $limite_affichage = 50;
    /**
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     * @Route("/accueil/recruteur", name="recruteur_front")
     */
    public function index(
        CandidatRepository $candidatRepository,
        RecruteurRepository $recruteurRepository,
        LikeRepository $likeRepository)
    {
        $candidats = array();
        $tabL = array();
        $tabC = array();
        // membre connecté
        $membre = $this->getUser();
        // info recruteur du membre
        $recruteur = $recruteurRepository->createQueryBuilder('r')
            ->join('r.membre', 'm')
            ->addSelect('m')
            ->where('r.membre = :membre')
            ->setParameter('membre', $membre)
            ->getQuery()
            ->getResult();
        // dump($recruteur)
        // like du recruteur
        $likeRecruteur = $likeRepository->createQueryBuilder('l')
            ->where('l.recruteur = :recruteur')
            ->setParameter('recruteur', $recruteur)
            ->andWhere('l.role_like = :roleLike')
            ->setParameter('roleLike', $membre->getRoleEmploi())
            ->getQuery()
            ->getResult();
        // id des candidats likés
        for( $l = 0; $l < count($likeRecruteur); $l++ ){
            $tabL[] = $likeRecruteur[$l]->getCandidat()->getId();
        }
        // tous les candidats
        $candidatsAll = $candidatRepository->findAll();
        // id de tous les candidats
        for( $c = 0; $c < count($candidatsAll); $c++ ){
            $tabC[] = $candidatsAll[$c]->getId();
        }
        // pour chaque candidat
        for( $iBcl1 = 0; $iBcl1 < count($tabC); $iBcl1++ ){
            // pour chaque candidat likés
            for( $iBcl2 = 0; $iBcl2 < count($tabL); $iBcl2++ ){
                if(array_key_exists($iBcl1, $tabC)){
                    // si le candidat est liké
                    if( $tabC[$iBcl1] === $tabL[$iBcl2] ){
                        // supprimer de la liste des candidats à afficher
                        unset($tabC[$iBcl1]);
                        $iBcl1++;
                    }
                }
            }
        }

        // nbr d'affichages
        if( count($tabC) > $this->limite_affichage ){
            $nbr_affichage = $this->limite_affichage;
        }
        else{
            $nbr_affichage = count($tabC);
        }
        // pour chaque candidat à afficher
        for($i = 0; $i < $nbr_affichage; $i++ ){
            $index = 0;
            // sélection aléatoire
            $index = array_rand($tabC);
            $id = $tabC[$index];
            // sélection des candidats
            $candidats[] = $candidatRepository->createQueryBuilder('c')
                ->join('c.membre', 'm')
                ->addSelect('m')
                ->where('c.id = :id')
                ->setParameter('id', $id)
                ->getQuery()
                ->getResult();
            // suppression dans la liste des candidats à afficher
            unset($tabC[$index]);

        }

        return $this->render('accueil_recruteur/index.html.twig', [
            'candidats' => $candidats,
            'id' => $recruteur[0]->getId(),
        ]);
    }

    
    /**
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     * @Route("/recruteur/profil/{id}", name="select_candidat")
     */
    public function selectCandidat(
        CandidatRepository $candidatRepository,
        RecruteurRepository $recruteurRepository,
        ObjectManager $objectManager,
        int $id)
    {
        $like = new Like();
        $membre = $this->getUser();
        $recruteur = $recruteurRepository->createQueryBuilder('r')
            ->where('r.membre = :membre')
            ->setParameter('membre', $membre)
            ->getQuery()
            ->getResult();
        $candidat = $candidatRepository->find($id);
        // dump($candidat);
        // dump($recruteur);
        $like->setCandidat( $candidat )
            ->setRecruteur( $recruteur[0] )
            ->setRoleLike( $membre->getRoleEmploi() )
            ->setDateLike( new \DateTime() );
        $objectManager->persist($like);
        $objectManager->flush();

        return $this->redirectToRoute('match_result', [ 'id' => $id ]);
    }
}

templates/recruteur_front/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('css/stylefrontrecruteur.css') }}" rel="stylesheet">
{% endblock %}

{% block title %}Hello RecruteurFrontController!{% endblock %}

{% block body %}
    {% include 'navbar_recruteur/index.html.twig' %}
    <style>
        .bdPhotoC{
            border: 2px solid #a2ddf7;
        }

        .bdPhotoR{
            border: 2px solid #b13f9a;
        }
    </style>
    <body id="page-top">

    <!--Début Recruteur Card-->
    <div class="row">
        <div class="col-lg-12">
            <div class="card mt-5 recruteur-top">
                <div class="card-body">
                    <div class="card border-0 mx-auto" style="width: 18rem;">
                        <img src="{{ app.user.photoProfil }}"
                             class="card-img-top img-responsive rounded-circle bdPhotoR mt-2  pt-1 pb-1 pr-1 pl-1 mx-auto"
                             alt="...">
                        <div class="card-body">
                            <h5 class="card-title text-center">{{ app.user.nom }} {{ app.user.prenom }}</h5>
                            <h6 class="card-title text-center font-weight-light text-black-50">{{ app.user.ville }}
                                ,{{ app.user.pays }}</h6>
                            <p class="card-text text-center">This is a longer card with supporting text below as a
                                natural lead-in
                                to
                                additional content. This content is a little bit longer.</p>
                            <button type="button"
                                    class="btn btn-lg rounded-pill pl-lg-5 pr-lg-5 col px-md-5 font-weight-bolder text-white">
                                Suivre
                            </button>
                        </div>
                    </div>
                </div>

                {# DébutZone Abonnements#}
                <ul class="list-group list-group-horizontal-lg border-0 pb-4 ">
                    <li class="list-group-item d-flex border-0 font-weight-bold mx-auto">
                        Abonnés:
                        <span class="badge badge-pill ml-2 font-weight-bolder text-white">400</span>
                    </li>
                    <li class="list-group-item d-flex border-0 font-weight-bold mx-auto">
                        Abonnements:
                        <span class="badge badge-pill ml-2 font-weight-bolder text-white">100</span>
                    </li>
                    <li class="list-group-item d-flex border-0 font-weight-bold mx-auto">
                        J'aime:
                        <span class="badge badge-pill ml-2 font-weight-bolder text-white ">50</span>
                    </li>
                </ul>
                {# Fin zone Abonnement#}
            </div>
        </div>
    </div>
    <!--Fin Recruteur Card-->


    <!-- Section Candidat  -->
    <section class="page-section candidat" id="candidat">
        <div class="container">

            <!--  Section Candidat  Heading -->
            <h2 class="page-section-heading text-center display-3 font-weight-bolder mb-0 text-candidat pb-2"><img
                        src="{{ asset('image/icon_card.png') }}" alt="iconecandidat"> &#8226; Candidats </h2>

            <hr>
            <!--  Fin de Section Candidat Heading -->
            <!-- Début cards section -->
            <div class="container pt-2" style="background-color: #f9f9f9;"> <!-- Début container cards -->
                <div class="card-deck">
                    {% for candidat in candidats %}
                        <div class="card">

                            <a href="{{ path('profil_details_candidat', { 'id' : candidat[0].id}) }}" class="text-center"><img src="{{ candidat[0].membre.photoProfil }}"
                                 class="card-img-top img-responsive rounded-circle bdPhotoC mt-2  pt-1 pb-1 pr-1 pl-1 mx-auto"
                                 alt="{{ candidat[0].membre.descriptionPhoto }}"></a>
                            <div class="card-body">
                                <h5 class="card-title text-center">{{ candidat[0].membre.nom }} {{ candidat[0].membre.prenom }}</h5>
                                <h6 class="card-title text-center font-weight-light text-black-50">{{ candidat[0].metier }}
                                    , {{ candidat[0].membre.ville }}
                                    ,{{ candidat[0].membre.pays }}</h6>
                                <p class="card-text text-center">This is a longer card with supporting text below as a
                                    natural
                                    lead-in to
                                    additional content. This content is a little bit longer.</p>
                                <p><a href="{{ path('select_candidat', {id: candidat[0].id}) }}" role="button"><i class="fas fa-plus-square fa-2x"></i></a></p>
                            </div>
                        </div>
                    {% endfor %}




                </div> <!-- Fin container cards -->
            </div>
            <!-- Fin cards section-->

        </div> <!-- /container -->
    </section>



    <!-- Footer -->
{% include 'footer/index.html.twig' %}
    <!-- Fin du Footer -->
{% endblock %}