src/Entity/Membre.php
<?php

namespace App\Entity;

use App\Validator\Mdp;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MembreRepository")
 * @UniqueEntity("email")
 */
class Membre implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank()
     * @Assert\Length(max=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank()
     * @Assert\Length(max=50)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=100, unique=true)
     * @Assert\NotBlank()
     * @Assert\Length(max=100)
     */
    private $email;

    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min=8, max=255)
     * @Mdp()
     */
    private $mdp;

    /**
     * @var string The hashed password
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank()
     * @Assert\Length(max=100)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank()
     * @Assert\Length(max=50)
     */
    private $pays;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Personnalite")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank()
     */
    private $personnalite;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $photo_profil;

    /**
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(max=255)
     */
    private $statut;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_inscription;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description_photo;

    /**
     * @ORM\Column(type="string", length=10)
     * @Assert\NotBlank()
     * @Assert\Length(max=10)
     */
    private $role_emploi;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        $this->username = $this->email;
        return (string) $this->username;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        $this->password = $this->mdp;
        return (string) $this->password;
    }

    public function getMdp(): ?string
    {
        return $this->mdp;
    }

    public function setMdp(string $mdp): self
    {
        $this->mdp = $mdp;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getPersonnalite(): ?Personnalite
    {
        return $this->personnalite;
    }

    public function setPersonnalite(?Personnalite $personnalite): self
    {
        $this->personnalite = $personnalite;

        return $this;
    }

    public function getPhotoProfil(): ?string
    {
        return $this->photo_profil;
    }

    public function setPhotoProfil(?string $photo_profil): self
    {
        $this->photo_profil = $photo_profil;

        return $this;
    }

    /**
     * Get the value of imageFile
     *
     * @return  File
     */ 
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * Set the value of imageFile
     *
     * @param  File  $imageFile
     *
     * @return  self
     */ 
    public function setImageFile(File $imageFile)
    {
        $this->imageFile = $imageFile;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = explode(',', $this->statut);
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getDateInscription(): ?\DateTimeInterface
    {
        return $this->date_inscription;
    }

    public function setDateInscription(\DateTimeInterface $date_inscription): self
    {
        $this->date_inscription = $date_inscription;

        return $this;
    }

    public function getDescriptionPhoto(): ?string
    {
        return $this->description_photo;
    }

    public function setDescriptionPhoto(string $description_photo): self
    {
        $this->description_photo = $description_photo;

        return $this;
    }

    public function getRoleEmploi(): ?string
    {
        return $this->role_emploi;
    }

    public function setRoleEmploi(string $role_emploi): self
    {
        $this->role_emploi = $role_emploi;

        return $this;
    }
}

src/Controller/MessageInterfaceController.php
<?php

namespace App\Controller;

use App\Entity\Message;
use App\Repository\MessageRepository;
use App\Repository\CandidatRepository;
use App\Repository\RecruteurRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MessageInterfaceController extends AbstractController
{

    /**
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     * @Route("/message/interface/{id}", name="message_interface")
     */
    public function index( 
        CandidatRepository $candidatRepository, 
        RecruteurRepository $recruteurRepository,
        int $id)
    {
        $membre = $this->getUser();

        if( $membre->getRoleEmploi() === 'candidat' ){
            $candidat = $candidatRepository->createQueryBuilder('c')
                ->join('c.membre', 'm')
                ->addSelect('m')
                ->where('c.membre = :membre')
                ->setParameter('membre', $membre)
                ->getQuery()
                ->getResult();

            $recruteur[0] = $recruteurRepository->find($id);

            $idUser = $candidat[0]->getId();
        }
        elseif( $membre->getRoleEmploi() === 'recruteur' ){
            $recruteur = $recruteurRepository->createQueryBuilder('r')
                ->join('r.membre', 'm')
                ->addSelect('m')
                ->where('r.membre = :membre')
                ->setParameter('membre', $membre)
                ->getQuery()
                ->getResult();

            $candidat[0] = $candidatRepository->find($id);

            $idUser = $recruteur[0]->getId();
        }

        
        return $this->render('message_interface/index.html.twig', [
            'id' => $id,
            'membre' => $membre,
            'candidat' => $candidat[0],
            'recruteur' => $recruteur[0],
            'idUser' => $idUser,
            'role' => $membre->getRoleEmploi(),
        ]);
        
    }

    /**
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     * @Route("ajax_message", name="ajax_message")
     */
    public function ajaxMessage( 
        MessageRepository $messageRepository,
        CandidatRepository $candidatRepository, 
        RecruteurRepository $recruteurRepository,
        ObjectManager $objectManager)
    {
        $membre = $this->getUser();

        $recruteur = $recruteurRepository->find( intval($_POST['recruteur']) );
        $candidat = $candidatRepository->find( intval($_POST['candidat']) );


        if( $_POST['message'] !== "" ){
            $message = new Message();

            $message->setCandidat( $candidat )
                ->setRecruteur( $recruteur )
                ->setAuteur( $membre->getRoleEmploi() )
                ->setMessage( $_POST['message'] )
                ->setDateMessage( new \DateTime() );

            $objectManager->persist( $message );
            $objectManager->flush();
        }

        
        $messages = $messageRepository->createQueryBuilder('m')
            ->where('m.candidat = :candidat')
            ->setParameter('candidat', $candidat)
            ->andWhere('m.recruteur = :recruteur')
            ->setParameter('recruteur', $recruteur)
            
            ->orderBy('m.date_message', 'ASC')

            ->join('m.candidat', 'c')
            ->addSelect('c')
            ->join('c.membre', 'mem1')
            ->addSelect('mem1')
            ->join('m.recruteur', 'r')
            ->addSelect('r')
            ->join('r.membre', 'mem2')
            ->addSelect('mem2')
            
            ->getQuery()
            ->getResult();
        
        
        /*
        $messages = $messageRepository->findAll();
        */
        

        $messages = array_map( function(Message $message){
            return [
                'nomCandidat' => $message->getCandidat()->getMembre()->getNom(),
                'prenomCandidat' => $message->getCandidat()->getMembre()->getPrenom(),
                'nomRecruteur' => $message->getRecruteur()->getMembre()->getNom(),
                'prenomRecruteur' => $message->getRecruteur()->getMembre()->getPrenom(),
                'date' => $message->getDateMessage(),
                'message' => $message->getMessage(),
                'auteur' => $message->getAuteur(),
            ];
        }, $messages );

        
        return $this->json( $messages );
        
    }
}

templates/message_interface/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MessageInterfaceController!{% endblock %}

{% block stylesheets %}
    {{ parent() }}

    <style>
    .bg-recruteur{
        background-color: #b13f9a;
    }

    .bg-candidat{
        background-color: #a2ddf7;
    }
    </style>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $(function(){
            console.log('Jquery chargé !');

            ajaxMessage();
            
            $('#submit').click( function(){
                console.log('bouton cliqué');

                ajaxMessage( $('#newMessage').val() );
                
            } );




            function ajaxMessage( messageSent = null ){
                $.post("{{ path('ajax_message') }}", {message : messageSent, candidat : $('#candidat').val(), recruteur : $('#recruteur').val() }, function(reponse){
                    // console.log(reponse);
                    $('#chat').children().remove();
                    $('#newMessage').val('');

                    reponse.forEach(element => {
                        var pMessage = document.createElement('p');
                        var spanMessage = document.createElement('span');
                        spanMessage.innerHTML = element.message;

                        if( element.auteur === $('#membreRole').val() ){
                            pMessage.setAttribute('class', 'text-right');
                        }
                        else{
                            pMessage.setAttribute('class', 'text-left');
                        }

                        if( element.auteur === 'candidat' ){
                            spanMessage.setAttribute('class', 'bg-candidat p-2 rounded');
                        }
                        else if( element.auteur === 'recruteur' ){
                            spanMessage.setAttribute('class', 'bg-recruteur p-2 rounded text-light');
                        }
                        pMessage.appendChild(spanMessage);
                        $('#chat').append(pMessage);
                    });
                }, 'json');
            }
        })
    </script>
{% endblock %}

{% block body %}
    {% if role == 'candidat' %}
        {% include 'navbar_candidat/index.html.twig' with { 'id' : idUser } %}
    {% elseif role == 'recruteur' %}
        {% include 'navbar_recruteur/index.html.twig' with { 'id' : idUser } %}
    {% endif %}

    <h1>Message</h1>
    <div id="chat" class="container border mb-3 rounded border-dark p-5"></div>
    <div class="form-group container">
        <input type="hidden" id="membreRole" name="membreRole" value="{{ membre.roleEmploi }}">
        <input type="hidden" id="recruteur" name="recruteur" value="{{ recruteur.id }}">
        <input type="hidden" id="candidat" name="candidat" value="{{ candidat.id }}">
        <input type="text" id="newMessage" name="newMessage" class="form-control d-inline-flex col-9">
        <button id="submit" class="btn btn-primary d-inlin-flex ml-5" role="btn" type="submit">Envoi</button>
    </div>
{% endblock %}