src/Entity/Message.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MessageRepository")
 */
class Message
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Candidat")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank()
     */
    private $candidat;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Recruteur")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank()
     */
    private $recruteur;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $message;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank()
     */
    private $date_message;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $auteur;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCandidat(): ?Candidat
    {
        return $this->candidat;
    }

    public function setCandidat(?Candidat $candidat): self
    {
        $this->candidat = $candidat;

        return $this;
    }

    public function getRecruteur(): ?Recruteur
    {
        return $this->recruteur;
    }

    public function setRecruteur(?Recruteur $recruteur): self
    {
        $this->recruteur = $recruteur;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getDateMessage(): ?\DateTimeInterface
    {
        return $this->date_message;
    }

    public function setDateMessage(\DateTimeInterface $date_message): self
    {
        $this->date_message = $date_message;

        return $this;
    }

    public function getAuteur(): ?string
    {
        return $this->auteur;
    }

    public function setAuteur(string $auteur): self
    {
        $this->auteur = $auteur;

        return $this;
    }
}

src/Form/MessageType.php
<?php

namespace App\Form;

use App\Entity\Message;
use App\Entity\Candidat;
use App\Entity\Recruteur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use PUGX\AutocompleterBundle\Form\Type\AutocompleteType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class MessageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('candidat', AutocompleteType::class, [
                'class' => Candidat::class,
                'label' => 'Candidat:'
            ]) 
            ->add('recruteur', AutocompleteType::class, [
                'class' => Recruteur::class,
                'label' => 'Recruteur:'
            ])
            ->add('auteur', ChoiceType::class, [
                'label' => 'Auteur',
                'choices' => [
                    'Candidat' => 'candidat',
                    'Recruteur' => 'recruteur',
                ]
            ])
            ->add('message', TextareaType::class, ['label' => 'Message'
            ])
            ->add('submit', SubmitType::class, ['label' => 'Enregistrer'
            ])
            ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Message::class,
        ]);
    }
}

src/Controller/MessageController.php
<?php

namespace App\Controller;

use App\Entity\Message;
use App\Form\MessageType;
use App\Repository\MessageRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MessageController extends AbstractController
{
    /**
     * URL + nom de la route
     * @Route("/message", name="message")
     */
    public function index( MessageRepository $messageRepository )
    {
        /*
            SELECT * FROM message
            $messages = $messageRepository->findAll();
        */

        /*
            SELECT * FROM message AS mes
            INNER JOIN candidat AS c
                ON mes.candidat = c.id
            INNER JOIN membre AS mem1
                ON c.membre = mem1.id
            INNER JOIN recruteur AS r
                ON mes.recruteur = r.id
            INNER JOIN membre AS mem2
                ON r.membre = mem2.id
        */
        $messages = $messageRepository->createQueryBuilder('mes')
        ->join('mes.candidat', 'c')
        ->addSelect('c')
        ->join('c.membre', 'mem1')
        ->addSelect('mem1')
        ->join('mes.recruteur', 'r')
        ->addSelect('r')
        ->join('r.membre', 'mem2')
        ->addSelect('mem2')
        ->getQuery()
        ->getResult();

        // Affichage des messages
        return $this->render('message/index.html.twig', [
            'messages' => $messages,
        ]);
    }

    /**
     * @Route("/message/add", name="message_add")
     * @Route("/message/edit/{id}", name="message_edit")
     */
    public function add(Request $request, ObjectManager $objectManager, Message $message = null)
    {
        //Adapter les 3 lignes ci-dessous selon la table en BDD
        //Il s'agit de la création du formulaire

        if ($message === null) {
            $message = new Message();
        }

        $messageForm = $this->createForm(MessageType::class, $message);
        $messageForm->handleRequest($request);

        //A la soumission du formulaire
        if( $messageForm->isSubmitted() && $messageForm->isValid() ){
            //Pour les champs de type DateTime, utiliser le setter() avec comme argument new \DateTime
            $message->setDateMessage( new \DateTime() );

            //Injection en BDD
            $objectManager->persist($message);
            $objectManager->flush();

            //Redirection vers l'affichage - Mettre en argument le nom de la route
            return $this->redirectToRoute('message');
        }

        //Rendu du formulaire
        return $this->render('message/add.html.twig', [
            'message_form' => $messageForm->createView(),
        ]);
    }

    /**
    * @Route("/message/delete/{id}", name="message_delete")
    */
    public function delete(Message $message, ObjectManager $objectManager){

        if( $message !== null ){
            $objectManager->remove($message);
            $objectManager->flush();
        }

        return $this->redirectToRoute('message');


    }
}

templates/message/add.html.twig
{% extends 'base.html.twig' %}


{% block title %}Hello MessageController!{% endblock %}

{% block body %}
    {{ form_start(message_form) }}
    {{ form_end(message_form) }}
{% endblock %}

{% block javascripts %}
	{#
<<<<<<< HEAD
	{% include "../../js/autocompleter_candidat.js" %}
	{% include "../../js/autocompleter_recruteur.js" %}
	{% include "../includes/auto_complete.html.twig" %}
=======
	{% include "autocompleter_candidat.js" %}
	{% include "autocompleter_recruteur.js" %}
	{% include "auto_complete.html.twig" %}
>>>>>>> message
	#}
{% endblock %}

templates/message/edit.html.twig
{% extends 'base.html.twig' %}


{% block title %}Hello MessageEdit!{% endblock %}

{% block body %}
    {{ form_start(message_form) }}
    {{ form_end(message_form) }}
{% endblock %}

{% block javascripts %}
	{#
	{% include "../../js/autocompleter_candidat.js" %}
	{% include "../../js/autocompleter_recruteur.js" %}
	{% include "../includes/auto_complete.html.twig" %}
	#}
{% endblock %}

templates/message/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MessageController!{% endblock %}

{% block body %}
{% include 'backoffice/navbar.html.twig' %}

<a href="{{ path('message_add') }}"><button type="button" class="btn btn-success">Ajouter un message</button></a>
<a class="btn btn-info" href="{{ path('match') }}">Liste des match</a>
<table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>candidat</th>
                <th>recruteur</th>
                <th>auteur</th>
                <th>message</th>
                <th>date message</th>
                <th>Options</th>
            </tr>
        </thead>
    
        <tbody>
            {# Pour chaque membre #}
            {% for message in messages %}
            <tr>
                <th>{{ message.id }}</th>
                <td>{{ message.candidat.id }} - {{ message.candidat.membre.nom }} {{ message.candidat.membre.prenom }}</td>
                <td>{{ message.recruteur.id }} - {{ message.recruteur.membre.nom }} {{ message.recruteur.membre.prenom }}</td>
                <td>{{ message.auteur }}</td>
                <td>{{ message.message }}</td>
                <td>{{ message.dateMessage|date('j/m/Y') }}</td>
                <td>
                    <a href="{{ path('message_edit', { 'id' : message.id }) }}"><i class="fas fa-pen"></i></a>
                    <a href="{{ path('message_delete', { 'id' : message.id }) }}"><i class="fas fa-trash-alt"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% include 'footer/index.html.twig' %}
{% endblock %}